### ISSUE TITLE
Error: Cannot find module '../dll/vendor-manifest.json'

### ISSUE THREAD

**Issue by uolter** [maciejtreder/angular-universal-pwa#103]
Hello I am trying to start the application from scratch in a Docker container but when I run the command **npm start**  I am getting the following error:

`
module.js:471
    throw err;
    ^
Error: Cannot find module '../dll/vendor-manifest.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at module.exports (/my-app/webpack/webpack.common.js:12:27)
    at module.exports (/my-app/webpack.config.js:20:45)
    at handleFunction (/my-app/node_modules/webpack/lib/prepareOptions.js:26:13)
    at prepareOptions (/my-app/node_modules/webpack/lib/prepareOptions.js:11:13)
    at requireConfig (/my-app/node_modules/webpack/bin/convert-argv.js:98:14)
    at /my-app/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (native)
    at module.exports (/my-app/node_modules/webpack/bin/convert-argv.js:102:15)
    at Object.<anonymous> (/my-app/node_modules/webpack-dev-server/bin/webpack-dev-server.js:223:50)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

npm info lifecycle angular-universal-serverless@1.0.0~webdev: Failed to exec webdev script
npm ERR! Linux 4.4.0-96-g`

**Step to Reproduce**

- Login into Docker Playground (https://labs.play-with-docker.com/) and start an instance
- Run the following coomand:
   >> git clone https://github.com/maciejtreder/angular-universal-pwa.git
   >> cd angular-universal-pwa
- Create the following **Dockefile**
    
    FROM node:6.10
    LABEL "author"="uolter"

    RUN apt-get update && apt-get install git -y

    COPY . /my-app
    WORKDIR /my-app

    RUN npm install

    EXPOSE 300
    ENTRYPOINT ["npm",  "start"]

- Build the application: 
    >> docker -t build uolter/angular-universal-pwa:latest
- Run the application:
    >> docker run -it --rm --name angular-universal -p 3000:3000 uolter/angular-universal-pwa:latest

Have I missed something? 
Can you help me to understand why I am getting this error?

**Comment by maciejtreder** [comment]
@uolter Could you try to reproduce this issue with the latest build? A lot have changed since you reported it. Especially in build process (app is migrated to Angular-CLI).
